// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Orenda.Web.Data;

#nullable disable

namespace Orenda.Web.Migrations
{
    [DbContext(typeof(OrendaDbContext))]
    [Migration("20260305191930_AddDepartmanVeTakim")]
    partial class AddDepartmanVeTakim
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Orenda.Web.Models.Departman", b =>
                {
                    b.Property<int>("DepartmanID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepartmanID"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("DepartmanID");

                    b.ToTable("Departmanlar", "gayemkaratas_OrendaAdmin");
                });

            modelBuilder.Entity("Orenda.Web.Models.Kullanici", b =>
                {
                    b.Property<int>("CalisanID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CalisanID"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("AktiflikDurumu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CihazTipi")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("DepartmanID")
                        .HasColumnType("int");

                    b.Property<string>("Eposta")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("HaftalikVerimlilikSkoru")
                        .HasColumnType("float");

                    b.Property<string>("KullaniciAdi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RfidID")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("RolID")
                        .HasColumnType("int");

                    b.Property<string>("Sifre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SifreHash");

                    b.Property<string>("SonGirisIP")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("TakimID")
                        .HasColumnType("int");

                    b.Property<string>("Telefon")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("CalisanID");

                    b.HasIndex("DepartmanID");

                    b.HasIndex("TakimID");

                    b.ToTable("Kisiler", "gayemkaratas_OrendaAdmin");
                });

            modelBuilder.Entity("Orenda.Web.Models.Takim", b =>
                {
                    b.Property<int>("TakimID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TakimID"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DepartmanID")
                        .HasColumnType("int");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("TakimID");

                    b.HasIndex("DepartmanID");

                    b.ToTable("Takimlar", "gayemkaratas_OrendaAdmin");
                });

            modelBuilder.Entity("Orenda.Web.Models.ToDo", b =>
                {
                    b.Property<int>("GorevNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GorevNo"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AtananCalisanID")
                        .HasColumnType("int");

                    b.Property<int?>("AtayanCalisanID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("BaslangicTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("BitisTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Durum")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("GorevNo");

                    b.HasIndex("AtananCalisanID");

                    b.ToTable("ToDo", "gayemkaratas_OrendaAdmin");
                });

            modelBuilder.Entity("Orenda.Web.Models.Kullanici", b =>
                {
                    b.HasOne("Orenda.Web.Models.Departman", "Departman")
                        .WithMany("Calisanlar")
                        .HasForeignKey("DepartmanID");

                    b.HasOne("Orenda.Web.Models.Takim", "Takim")
                        .WithMany("Uyeler")
                        .HasForeignKey("TakimID");

                    b.Navigation("Departman");

                    b.Navigation("Takim");
                });

            modelBuilder.Entity("Orenda.Web.Models.Takim", b =>
                {
                    b.HasOne("Orenda.Web.Models.Departman", "Departman")
                        .WithMany("Takimlar")
                        .HasForeignKey("DepartmanID");

                    b.Navigation("Departman");
                });

            modelBuilder.Entity("Orenda.Web.Models.ToDo", b =>
                {
                    b.HasOne("Orenda.Web.Models.Kullanici", "AtananKisi")
                        .WithMany()
                        .HasForeignKey("AtananCalisanID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AtananKisi");
                });

            modelBuilder.Entity("Orenda.Web.Models.Departman", b =>
                {
                    b.Navigation("Calisanlar");

                    b.Navigation("Takimlar");
                });

            modelBuilder.Entity("Orenda.Web.Models.Takim", b =>
                {
                    b.Navigation("Uyeler");
                });
#pragma warning restore 612, 618
        }
    }
}
