// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Orenda.Web.Data;

#nullable disable

namespace Orenda.Web.Migrations
{
    [DbContext(typeof(OrendaDbContext))]
    [Migration("20260504085733_AddMessagingSystemFixed")]
    partial class AddMessagingSystemFixed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Orenda.Web.Models.Cihaz", b =>
                {
                    b.Property<int>("CihazID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CihazID"));

                    b.Property<int?>("AtananCalisanID")
                        .HasColumnType("int");

                    b.Property<string>("CihazAdi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Durum")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("SeriNo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Tür")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("CihazID");

                    b.HasIndex("AtananCalisanID");

                    b.ToTable("Cihazlar");
                });

            modelBuilder.Entity("Orenda.Web.Models.Departman", b =>
                {
                    b.Property<int>("DepartmanID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepartmanID"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("DepartmanID");

                    b.ToTable("Departmanlar", "gayemkaratas_OrendaAdmin");
                });

            modelBuilder.Entity("Orenda.Web.Models.GorevAdimi", b =>
                {
                    b.Property<int>("AdimID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdimID"));

                    b.Property<int?>("AgirlikYuzdesi")
                        .HasColumnType("int");

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("GorevNo")
                        .HasColumnType("int");

                    b.Property<bool>("TamamlandiMi")
                        .HasColumnType("bit");

                    b.HasKey("AdimID");

                    b.HasIndex("GorevNo");

                    b.ToTable("GorevAdimlari", "gayemkaratas_OrendaAdmin");
                });

            modelBuilder.Entity("Orenda.Web.Models.Izin", b =>
                {
                    b.Property<int>("IzinID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IzinID"));

                    b.Property<DateTime>("BaslangicTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("BitisTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("CalisanID")
                        .HasColumnType("int");

                    b.Property<string>("Durum")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Sebep")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("YöneticiNotu")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("IzinID");

                    b.HasIndex("CalisanID");

                    b.ToTable("Izinler");
                });

            modelBuilder.Entity("Orenda.Web.Models.Kullanici", b =>
                {
                    b.Property<int>("CalisanID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CalisanID"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("AktiflikDurumu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CihazTipi")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("DepartmanID")
                        .HasColumnType("int");

                    b.Property<string>("Eposta")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GlobalID")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<double>("HaftalikVerimlilikSkoru")
                        .HasColumnType("float");

                    b.Property<DateTime>("IseBaslamaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("KullaniciAdi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RfidID")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("RolID")
                        .HasColumnType("int");

                    b.Property<string>("Sifre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("SifreHash");

                    b.Property<string>("SirketKodu")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("SonGirisIP")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("TakimID")
                        .HasColumnType("int");

                    b.Property<string>("Telefon")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int>("YillikIzinHakki")
                        .HasColumnType("int");

                    b.HasKey("CalisanID");

                    b.HasIndex("DepartmanID");

                    b.HasIndex("TakimID");

                    b.ToTable("Kisiler", "gayemkaratas_OrendaAdmin");
                });

            modelBuilder.Entity("Orenda.Web.Models.Mesaj", b =>
                {
                    b.Property<int>("MesajID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MesajID"));

                    b.Property<int>("AliciID")
                        .HasColumnType("int");

                    b.Property<string>("FotografUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("GonderenID")
                        .HasColumnType("int");

                    b.Property<DateTime>("GonderilmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Icerik")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<bool>("OkunduMu")
                        .HasColumnType("bit");

                    b.HasKey("MesajID");

                    b.HasIndex("AliciID");

                    b.HasIndex("GonderenID");

                    b.ToTable("Mesajlar");
                });

            modelBuilder.Entity("Orenda.Web.Models.SaglikVerisi", b =>
                {
                    b.Property<int>("SaglikVerisiID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SaglikVerisiID"));

                    b.Property<int>("AdimSayisi")
                        .HasColumnType("int");

                    b.Property<int>("CalisanID")
                        .HasColumnType("int");

                    b.Property<int>("Nabiz")
                        .HasColumnType("int");

                    b.Property<DateTime>("TarihSaat")
                        .HasColumnType("datetime2");

                    b.Property<double?>("UykuSaati")
                        .HasColumnType("float");

                    b.HasKey("SaglikVerisiID");

                    b.HasIndex("CalisanID");

                    b.ToTable("SaglikVerileri", "gayemkaratas_OrendaAdmin");
                });

            modelBuilder.Entity("Orenda.Web.Models.SistemLog", b =>
                {
                    b.Property<int>("LogID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogID"));

                    b.Property<string>("IPAdresi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("IslemDetayi")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("IslemTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("IslemTipi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("KullaniciID")
                        .HasColumnType("int");

                    b.HasKey("LogID");

                    b.HasIndex("KullaniciID");

                    b.ToTable("SistemLoglari", "gayemkaratas_OrendaAdmin");
                });

            modelBuilder.Entity("Orenda.Web.Models.SohbetIstegi", b =>
                {
                    b.Property<int>("IstekID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IstekID"));

                    b.Property<int>("AliciID")
                        .HasColumnType("int");

                    b.Property<string>("Durum")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("GonderenID")
                        .HasColumnType("int");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("IstekID");

                    b.HasIndex("AliciID");

                    b.HasIndex("GonderenID");

                    b.ToTable("SohbetIstekleri");
                });

            modelBuilder.Entity("Orenda.Web.Models.Takim", b =>
                {
                    b.Property<int>("TakimID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TakimID"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DepartmanID")
                        .HasColumnType("int");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("TakimID");

                    b.HasIndex("DepartmanID");

                    b.ToTable("Takimlar", "gayemkaratas_OrendaAdmin");
                });

            modelBuilder.Entity("Orenda.Web.Models.Talep", b =>
                {
                    b.Property<int>("TalepID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TalepID"));

                    b.Property<int>("CalisanID")
                        .HasColumnType("int");

                    b.Property<string>("Durum")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Konu")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Mesaj")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Tür")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Yanit")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("TalepID");

                    b.HasIndex("CalisanID");

                    b.ToTable("Talepler");
                });

            modelBuilder.Entity("Orenda.Web.Models.ToDo", b =>
                {
                    b.Property<int>("GorevNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GorevNo"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("AtananCalisanID")
                        .HasColumnType("int");

                    b.Property<int?>("AtayanCalisanID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("BaslangicTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("BitisTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Durum")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("OnayDurumu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("OnayNotu")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("TakimID")
                        .HasColumnType("int");

                    b.HasKey("GorevNo");

                    b.HasIndex("AtananCalisanID");

                    b.HasIndex("TakimID");

                    b.ToTable("ToDo", "gayemkaratas_OrendaAdmin");
                });

            modelBuilder.Entity("Orenda.Web.Models.Cihaz", b =>
                {
                    b.HasOne("Orenda.Web.Models.Kullanici", "AtananCalisan")
                        .WithMany()
                        .HasForeignKey("AtananCalisanID");

                    b.Navigation("AtananCalisan");
                });

            modelBuilder.Entity("Orenda.Web.Models.GorevAdimi", b =>
                {
                    b.HasOne("Orenda.Web.Models.ToDo", "ToDoTutucu")
                        .WithMany("Adimlar")
                        .HasForeignKey("GorevNo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ToDoTutucu");
                });

            modelBuilder.Entity("Orenda.Web.Models.Izin", b =>
                {
                    b.HasOne("Orenda.Web.Models.Kullanici", "Calisan")
                        .WithMany()
                        .HasForeignKey("CalisanID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Calisan");
                });

            modelBuilder.Entity("Orenda.Web.Models.Kullanici", b =>
                {
                    b.HasOne("Orenda.Web.Models.Departman", "Departman")
                        .WithMany("Calisanlar")
                        .HasForeignKey("DepartmanID");

                    b.HasOne("Orenda.Web.Models.Takim", "Takim")
                        .WithMany("Uyeler")
                        .HasForeignKey("TakimID");

                    b.Navigation("Departman");

                    b.Navigation("Takim");
                });

            modelBuilder.Entity("Orenda.Web.Models.Mesaj", b =>
                {
                    b.HasOne("Orenda.Web.Models.Kullanici", "Alici")
                        .WithMany()
                        .HasForeignKey("AliciID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Orenda.Web.Models.Kullanici", "Gonderen")
                        .WithMany()
                        .HasForeignKey("GonderenID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Alici");

                    b.Navigation("Gonderen");
                });

            modelBuilder.Entity("Orenda.Web.Models.SaglikVerisi", b =>
                {
                    b.HasOne("Orenda.Web.Models.Kullanici", "Kullanici")
                        .WithMany("SaglikVerileri")
                        .HasForeignKey("CalisanID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("Orenda.Web.Models.SistemLog", b =>
                {
                    b.HasOne("Orenda.Web.Models.Kullanici", "Kullanici")
                        .WithMany()
                        .HasForeignKey("KullaniciID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("Orenda.Web.Models.SohbetIstegi", b =>
                {
                    b.HasOne("Orenda.Web.Models.Kullanici", "Alici")
                        .WithMany()
                        .HasForeignKey("AliciID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Orenda.Web.Models.Kullanici", "Gonderen")
                        .WithMany()
                        .HasForeignKey("GonderenID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Alici");

                    b.Navigation("Gonderen");
                });

            modelBuilder.Entity("Orenda.Web.Models.Takim", b =>
                {
                    b.HasOne("Orenda.Web.Models.Departman", "Departman")
                        .WithMany("Takimlar")
                        .HasForeignKey("DepartmanID");

                    b.Navigation("Departman");
                });

            modelBuilder.Entity("Orenda.Web.Models.Talep", b =>
                {
                    b.HasOne("Orenda.Web.Models.Kullanici", "Calisan")
                        .WithMany()
                        .HasForeignKey("CalisanID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Calisan");
                });

            modelBuilder.Entity("Orenda.Web.Models.ToDo", b =>
                {
                    b.HasOne("Orenda.Web.Models.Kullanici", "AtananKisi")
                        .WithMany()
                        .HasForeignKey("AtananCalisanID");

                    b.HasOne("Orenda.Web.Models.Takim", "Takim")
                        .WithMany()
                        .HasForeignKey("TakimID");

                    b.Navigation("AtananKisi");

                    b.Navigation("Takim");
                });

            modelBuilder.Entity("Orenda.Web.Models.Departman", b =>
                {
                    b.Navigation("Calisanlar");

                    b.Navigation("Takimlar");
                });

            modelBuilder.Entity("Orenda.Web.Models.Kullanici", b =>
                {
                    b.Navigation("SaglikVerileri");
                });

            modelBuilder.Entity("Orenda.Web.Models.Takim", b =>
                {
                    b.Navigation("Uyeler");
                });

            modelBuilder.Entity("Orenda.Web.Models.ToDo", b =>
                {
                    b.Navigation("Adimlar");
                });
#pragma warning restore 612, 618
        }
    }
}
